#!/bin/bash
MAINVER=0.7.5
echo Clearing ~freenet-buildwin
rm -Rf ~freenet-buildwin/*
rm -Rf ~freenet-buildwin/.[a-zA-Z0-9]*
mkdir ~freenet-buildwin/.ssh
cat ~/.ssh/id_rsa.pub > ~freenet-buildwin/.ssh/authorized_keys
chmod 700 ~freenet-buildwin/.ssh
mkdir ~freenet-buildwin/bin
(echo "cd tmp" ; echo "cd app-wininstaller" ; echo "wine cmd /c build.cmd") > ~freenet-buildwin/bin/build-alpha
mkdir ~freenet-buildwin/tmp
cp -a /usr/src/cvs/eclipse-workspace/app-wininstaller ~freenet-buildwin/tmp
(cd ~freenet-buildwin/tmp/app-wininstaller; git checkout alpha)
echo Copied
GITVERSION=`cd ~freenet-buildwin/tmp/app-wininstaller && git describe --always --abbrev=40`
if [[ -z $GITVERSION ]]; then echo Could not get git version; exit 1; fi
echo Git version is $GITVERSION
rm -Rf ~freenet-buildwin/tmp/app-wininstaller/.git
mkdir ~freenet-buildwin/tmp/app-wininstaller/lib

# Copy files

ln -s /usr/src/cvs/eclipse-workspace/FreenetReleased/freenet.jar ~freenet-buildwin/tmp/app-wininstaller/res/install_node/freenet.jar || exit
ln -s /usr/src/cvs/eclipse-workspace/FreenetReleased/freenet-ext.jar ~freenet-buildwin/tmp/app-wininstaller/res/install_node/freenet-ext.jar || exit
cp ~toad/seednodes.fref ~freenet-buildwin/tmp/app-wininstaller/res/install_node/seednodes.fref || exit
for x in JSTUN KeyUtils ThawIndexBrowser UPnP Library; do
  ln -s /usr/src/cvs/eclipse-workspace/FreenetReleased/${x}.jar ~freenet-buildwin/tmp/app-wininstaller/res/install_node/plugins/${x}.jar || exit
done
cp ~freenet-buildwin/tmp/app-wininstaller/bin/Ahk2Exe.exe ~freenet-buildwin/tmp/app-wininstaller/bin/AutoHotkeySC.bin ~freenet-buildwin/tmp/app-wininstaller/res/tool_ahk/
echo Copied dependancies.

VERSION=`cat /usr/src/cvs/eclipse-workspace/FreenetReleased/freenet.build`
echo VERSION is $VERSION
echo Updating build
(cd ~freenet-buildwin/tmp/app-wininstaller; cat src/freenetinstaller/FreenetInstaller_Include_Info.inc | sed "s/_Inc_FreenetBuild = \#[0-9]\\+/_Inc_FreenetBuild = \#$VERSION/" > 1; cat 1 > src/freenetinstaller/FreenetInstaller_Include_Info.inc; cat 1)
chown -R freenet-buildwin.freenet-buildwin ~freenet-buildwin
chmod +x ~freenet-buildwin/bin/build-alpha
echo Running the build
rm ~freenet-buildwin/tmp/app-wininstaller/bin/*
eval `ssh-agent -s`
ssh-add
ssh -n freenet-buildwin@localhost xvfb-run ~freenet-buildwin/bin/build-alpha
kill -9 `pgrep -u freenet-buildwin`
cd
mkdir -p tmp-wi
cd tmp-wi
rm /root/tmp-wi/*
cp ~freenet-buildwin/tmp/app-wininstaller/bin/FreenetInstaller.exe FreenetInstaller-${VERSION}.exe
cd ~freenet-buildwin/tmp/app-wininstaller/res/install_node/updater/ || exit
cp update.cmd update-new.cmd || exit
sha1sum update-new.cmd > update-new.cmd.sha1 || exit
sha1sum update.cmd > update.cmd.sha1 || exit
cd ~/tmp-wi

#Uncomment if just want it for testing.
#echo Built it, file is in `pwd`
#exit

rsync ~freenet-buildwin/tmp/app-wininstaller/res/install_node/updater/update*cmd* osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/update/

echo Uploading
cp FreenetInstaller-${VERSION}.exe ~toad/
echo Signing
su - toad -c "gpg --sign --detach-sign FreenetInstaller-${VERSION}.exe"
cp ~toad/FreenetInstaller-${VERSION}.exe.sig .
echo Uploading to Google Code
#/root/bin/googlecode_upload.py -s "Freenet $MAINVER build $VERSION Windows installer" -p freenet -u matthew.toseland FreenetInstaller-alpha-${VERSION}.exe || exit
cp FreenetInstaller-${VERSION}.exe ~browser/
chmod a+r ~browser/FreenetInstaller-${VERSION}.exe
echo Uploading to emu
rsync -v FreenetInstaller-${VERSION}.exe* osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/installer/
cp FreenetInstaller-${VERSION}.exe* /usr/src/cvs/eclipse-workspace/FreenetReleased/
ssh osprey.vm.bytemark.co.uk -- "cp /var/www/downloads/alpha/.registry .; cat /var/www/downloads/alpha/.registry | sed \"s/FreenetInstaller.exe .*$/FreenetInstaller.exe installer\/FreenetInstaller-${VERSION}.exe/\" > new-registry ; cat new-registry > /var/www/downloads/alpha/.registry"

cp ~freenet-buildwin/tmp/app-wininstaller/res/install_node/wrapper/freenetwrapper.exe ~freenet-buildwin/tmp/app-wininstaller/bin/wrapper-windows-x86-32.exe || exit

cp ~freenet-buildwin/tmp/app-wininstaller/res/install_node/wrapper/wrapper-windows-x86-32.dll ~freenet-buildwin/tmp/app-wininstaller/bin/ || exit

cd ~freenet-buildwin/tmp/app-wininstaller/bin/
mv freenetlauncher.exe freenetlauncher-new.exe

for name in wrapper-windows-x86-32.exe wrapper-windows-x86-32.dll freenetlauncher-new.exe; do

cd ~freenet-buildwin/tmp/app-wininstaller/bin/

echo Uploading ${name} version ${GITVERSION}

mv $name ${name}.${GITVERSION}
sha1sum ${name}.${GITVERSION} > ${name}.${GITVERSION}.sha1
rsync -v ${name}.${GITVERSION}* osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/installer/

ssh osprey.vm.bytemark.co.uk -- "cat /var/www/downloads/alpha/.registry | sed \"s/$name .*$/${name} installer\/${name}.${GITVERSION}/\" > new-registry ; cat new-registry > /var/www/downloads/alpha/.registry"

done

ssh-agent -k

# Doesn't work, why?
#echo "http://downloads.freenetproject.org/alpha/installer/FreenetInstaller-${VERSION}.exe" > FreenetInstaller.exe.url
#rsync -vz FreenetInstaller.exe.url osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/installer/FreenetInstaller.exe.url
echo Now upload ~browser/FreenetInstaller-${VERSION}.exe to Google Code!
