#!/bin/bash
MAINVER=0.7.5
rm -Rf ~freenet-buildwin/*
rm -Rf ~freenet-buildwin/.[a-zA-Z0-9]*
mkdir ~freenet-buildwin/.ssh
cat ~/.ssh/id_rsa.pub > ~freenet-buildwin/.ssh/authorized_keys
chmod 700 ~freenet-buildwin/.ssh
mkdir ~freenet-buildwin/bin
(echo "cd tmp" ; echo "cd app-wininstaller" ; echo "wine cmd /c BuildAll.cmd") > ~freenet-buildwin/bin/build
mkdir ~freenet-buildwin/tmp
cp -a /usr/src/cvs/eclipse-workspace/app-wininstaller ~freenet-buildwin/tmp
(cd ~freenet-buildwin/tmp/app-wininstaller; git checkout master)
echo Copied
GITVERSION=`cd ~freenet-buildwin/tmp/app-wininstaller && git describe --always --abbrev=40`
if [[ -z $GITVERSION ]]; then echo Could not get git version; exit 1; fi
rm -Rf ~freenet-buildwin/tmp/app-wininstaller/.git
mkdir ~freenet-buildwin/tmp/app-wininstaller/lib
ln -s ~freenet-buildwin/tmp/app-wininstaller/bin/freenet.jar ~freenet-buildwin/tmp/app-wininstaller/lib/freenet-cvs-snapshot.jar
cp ~toad/seednodes.fref ~freenet-buildwin/tmp/app-wininstaller/src_freenetinstaller/files_install/seednodes.fref
VERSION=`getversion ~freenet-buildwin/tmp/app-wininstaller/`
echo VERSION is $VERSION
(cd ~freenet-buildwin/tmp/app-wininstaller; cat src_freenetinstaller/FreenetInstaller_Include_Info.inc | sed "s/_Inc_FreenetBuild = \#[0-9]\\+/_Inc_FreenetBuild = \#$VERSION/" > 1; cat 1 > src_freenetinstaller/FreenetInstaller_Include_Info.inc; cat 1)
chown -R freenet-buildwin.freenet-buildwin ~freenet-buildwin
chmod +x ~freenet-buildwin/bin/build
eval `ssh-agent -s`
ssh-add
ssh -n freenet-buildwin@localhost xvfb-run ~freenet-buildwin/bin/build
kill -9 `pgrep -u freenet-buildwin`
cd
mkdir tmp-wi
cd tmp-wi
cp ~freenet-buildwin/tmp/app-wininstaller/bin/FreenetInstaller.exe FreenetInstaller-${VERSION}-old.exe
(cd ~freenet-buildwin/tmp/app-wininstaller/src_freenetinstaller/files_install/; cp update.cmd update-new.cmd; sha1sum update-new.cmd > update-new.cmd.sha1; sha1sum update.cmd > update.cmd.sha1)
rsync ~freenet-buildwin/tmp/app-wininstaller/src_freenetinstaller/files_install/update*cmd* osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/update/
cp FreenetInstaller-${VERSION}-old.exe ~toad/
su - toad -c "gpg --sign --detach-sign FreenetInstaller-${VERSION}-old.exe"
cp ~toad/FreenetInstaller-${VERSION}-old.exe.sig .
echo Uploading to Google Code
cp FreenetInstaller-${VERSION}-old.exe ~browser/
chmod a+r ~browser/FreenetInstaller-${VERSION}-old.exe
echo Uploading to emu
rsync -v FreenetInstaller-${VERSION}-old.exe* osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/installer/
cp FreenetInstaller-${VERSION}-old.exe* /usr/src/cvs/eclipse-workspace/FreenetReleased/
ssh osprey.vm.bytemark.co.uk -- "cp /var/www/downloads/alpha/.registry .; cat /var/www/downloads/alpha/.registry | sed \"s/FreenetInstaller-old.exe .*$/FreenetInstaller-old.exe installer\/FreenetInstaller-${VERSION}-old.exe/\" > new-registry ; cat new-registry > /var/www/downloads/alpha/.registry"

cp ~freenet-buildwin/tmp/app-wininstaller/src_freenetinstaller/files_install/bin/wrapper-windows-x86-32.exe ~freenet-buildwin/tmp/app-wininstaller/bin/

cp ~freenet-buildwin/tmp/app-wininstaller/src_freenetinstaller/files_install/lib/wrapper-windows-x86-32.dll ~freenet-buildwin/tmp/app-wininstaller/bin/

for name in wrapper-windows-x86-32.exe wrapper-windows-x86-32.dll start.exe stop.exe freenetlauncher.exe; do

cd ~freenet-buildwin/tmp/app-wininstaller/bin/

echo Uploading ${name} version ${GITVERSION}

mv $name ${name}.${GITVERSION}
sha1sum ${name}.${GITVERSION} > ${name}.${GITVERSION}.sha1
rsync -v ${name}.${GITVERSION}* osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/installer/

ssh osprey.vm.bytemark.co.uk -- "cat /var/www/downloads/alpha/.registry | sed \"s/$name .*$/${name} installer\/${name}.${GITVERSION}/\" > new-registry ; cat new-registry > /var/www/downloads/alpha/.registry"

done

# Doesn't work, why?
#echo "http://downloads.freenetproject.org/alpha/installer/FreenetInstaller-${VERSION}.exe" > FreenetInstaller.exe.url
#rsync -vz FreenetInstaller.exe.url osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/installer/FreenetInstaller.exe.url
echo Now upload ~browser/FreenetInstaller-${VERSION}-old.exe to Google Code!
ssh-agent -k
