#!/usr/bin/env python3
import xml.etree.ElementTree as ElementTree
import argparse

parser = argparse.ArgumentParser(description="""
Filters non-text data from ResX. (Comments, processing instructions,
and document type declarations too.)""")
# See https://docs.python.org/3.4/library/xml.etree.elementtree.html#parsing-xml

parser.add_argument("in_path")
parser.add_argument("out_path")
parser.add_argument("filter", nargs="?", help="Additional names to filter.",
                    default=[])

args = parser.parse_args()

tree = ElementTree.parse(args.in_path)
root = tree.getroot()

filtered_data_elements = []

for element in root.iterfind("data"):
    name = element.get("name")
    if name:
        if not name.endswith(".Text") or name in args.filter:
            filtered_data_elements.append(element)

for element in filtered_data_elements:
    root.remove(element)

tree.write(args.out_path)
