#!/bin/bash
cd /root
echo SYNCING FULL BACKUP OF OSPREY.VM.BYTEMARK.CO.UK
mv osprey.full.backup.prevprev osprey.full.backup.previous
rm -Rf osprey.full.backup.previous
echo COPYING PREVIOUS BACKUP
cp -a osprey.full.backup osprey.full.backup.previous
echo SYNCING...
mkdir -p osprey.full.backup
chmod 700 osprey.full.backup
rsync -avzx osprey.vm.bytemark.co.uk:/ osprey.full.backup/backup
echo SYNCED
