#!/bin/bash
# Put the real keys in ~/bin/insert-update-keys
source ~/bin/insert-update-keys
VERSION=12
FILENAME=/var/lib/freenet-experimental/freenet-ext.${VERSION}.jar
rsync emu.freenetproject.org:/var/www/downloads/alpha/freenet-ext.jar ${FILENAME}
/root/bin/insert-update-inner 9481 $FILENAME "${OLDKEY}/ext-$VERSION" ext-update-old-$VERSION 1 &
/root/bin/insert-update-inner 9481 $FILENAME "${NEWKEY}/ext-$VERSION" ext-update-new-$VERSION 0 &
/root/bin/insert-update-inner 7482 $FILENAME "${OLDKEY}/ext-$VERSION" ext-update-old-$VERSION 1 &
/root/bin/insert-update-inner 7482 $FILENAME "${NEWKEY}/ext-$VERSION" ext-update-new-$VERSION 0 &

jobs
wait %1
wait %2
wait %3
wait %4
