#!/bin/bash

#
# Build a plugin, push it to the webserver, update the URL registry, and insert
# it to a CHK with the node on port 9481.
#

# Shared default configuration and utility functions.
source freenet-scripts-common || exit
readConfig

if [[ -z "$1" ]]; then
	cat <<EOF Usage: $0 [plugin name]

Requires that "$freenetRoot/plugin-[plugin name]" contains a repository.
EOF
	exit 1
fi

plugin="$1"

makeBuildDir
git clone "$freenetRoot/plugin-$plugin" "$buildDir/$plugin" || exit 11
echo "Clone complete"

pushd "$buildDir"
ln -s "$fredDir" "fred"
pushd "$plugin"

ant clean || exit 2
ant distclean
ant || exit 3

# TODO: Should this always release the current HEAD? Not the latest tag?
gitVersion="$(git describe --always --abbrev=40)"
name="$plugin-$gitVersion"
# For a plugin with underscores in its name (like Freemail_wot) the build
# product is expected to be named just that before the first underscore.
distJarName="$(echo $plugin | cut -d "_" -f 1).jar"
jarName="$name.jar"
mv "dist/$distJarName" "$jarName" || exit 4
sha1sum "$jarName" > "$jarName.sha1"

sourceName="$name-source.tar.bz2"
git archive --format=tar "$gitVersion" | bzip2 -cz > "$sourceName"
# TODO: Is a source archive checksum desirable?

require "Release $name?"

cp "$jarName" "$releaseDir/$plugin.jar" || exit 5

eval "$(ssh-agent -s)"
ssh-add
rsync -vz "$jarName"* "${targetHost}:/var/www/downloads/alpha/plugins/$plugin/" || exit 6
echo Uploaded jar
rsync -vz "$sourceName" "${targetHost}:/var/www/downloads/alpha/plugins/" || exit 7
echo Uploaded source

urlName="$plugin.jar.url"
echo "https://downloads.freenetproject.org/alpha/plugins/$plugin/$jarName" > "$urlName"
sha1sum "$urlName" > "$urlName.sha1"

rsync -vz "$urlName"* "${targetHost}:/var/www/downloads/alpha/plugins/" || exit 8
ssh $targetHost -- "sed -i \"s/$plugin.jar .*$/$plugin.jar plugins\\/$plugin\\/$jarName/\" /var/www/downloads/alpha/.registry" || exit 9
echo Updated registry

echo Started insert
nc "$fcpHost" "$fcpPort" - <<EOF
ClientHello
Name=$jarName-inserter
ExpectedVersion=2
End
ClientPut
URI=CHK@
Identifier=$jarName
Verbosity=1023
MaxRetries=-1
UploadFrom=disk
Filename=$releaseDir/$plugin.jar
DataLength=$(ls -l $jarName | cut -d " " -f 5)
TargetFilename=$plugin.jar
Persistence=forever
PriorityClass=2
Global=true
End
EOF
popd
