#!/bin/bash

# Load configuration and utility functions.
source freenet-scripts-common || exit

getBuildInfo
if [[ -z "$gitVersion" ]]; then echo Could not get git version; exit 4; fi
echo Version is $buildNumber

makeBuildDir
ln -s $(pwd) "$buildDir/scripts"
git clone "$installerDir" "$buildDir/java_installer" || exit

pushd "$buildDir/java_installer"
mkdir lib

cp "$freenetExtPath" bin/freenet-ext.jar || exit
cp "$releaseDir/freenet.jar" bin/freenet.jar || exit
cp "$seedrefsPath" bin/seednodes.fref || exit
cp "$bcprovPath" bin/ || exit
cp "$releaseDir/dependencies/standalone-compiler.jar" lib/ || exit

# Build script uses environment variables.
export jarsignerStoreLocation="$jarsignerStoreLocation"
export jarsignerStorePassword="$jarsignerStorePassword"
export jarsignerAlias="$jarsignerAlias"
export jarsignerCodeSigningKeyPassword="$jarsignerCodeSigningKeyPassword"

./build-all.sh || exit

cp res/bin/sha1test.jar . || exit

cp dist/* . || exit

../scripts/sign-installer-files . || exit

mv new_installer_offline.jar new_installer_offline_${buildNumber}.jar || exit 8
mv new_installer_offline.jar.sig new_installer_offline_${buildNumber}.jar.sig || exit 9
mv new_installer_offline_${buildNumber}.jar* $releaseDir || exit 10
