#!/bin/bash
su - toad -c "cd /usr/src/cvs/eclipse-workspace/app-new_installer; ./build-all.sh"
VERSION=`cat /usr/src/cvs/eclipse-workspace/FreenetReleased/freenet.build`
#VERSION=1219-mac-install-fix
echo Version is $VERSION
TEMPDIR=`mktemp -d`
cp /usr/src/cvs/eclipse-workspace/app-new_installer/dist/* $TEMPDIR
cd $TEMPDIR
echo Copied to $TEMPDIR
echo Signing the jars
for i in $(ls -1 *jar); do jarsigner -storepass azerty $i emu; done
cp *jar /usr/src/cvs/eclipse-workspace/app-new_installer/dist/
sux - toad /home/toad/bin/sign-installer-jars
cp /usr/src/cvs/eclipse-workspace/app-new_installer/dist/*jar.sig .
(cd /usr/src/cvs/eclipse-workspace/app-new_installer/scripts/; sha1sum update.cmd > update.cmd.sha1; sha1sum update.sh > update.sh.sha1; cd /usr/src/cvs/eclipse-workspace/app-new_installer/res/; sha1sum wrapper.conf > wrapper.conf.sha1)
eval `ssh-agent -s`
ssh-add
rsync /usr/src/cvs/eclipse-workspace/app-new_installer/scripts/update.* /usr/src/cvs/eclipse-workspace/app-new_installer/res/wrapper.conf* osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/update/
cp new_installer_offline.jar new_installer_offline_${VERSION}.jar
cp new_installer_offline.jar.sig new_installer_offline_${VERSION}.jar.sig
ls -l new_installer_offline_${VERSION}.jar
cp new_installer_offline_${VERSION}.jar new_installer_offline_${VERSION}.jar.sig ~browser/
cp new_installer_offline_${VERSION}.jar* /usr/src/cvs/eclipse-workspace/FreenetReleased/
rm new_installer_offline_${VERSION}.jar new_installer_offline_${VERSION}.jar.sig
chmod a+r ~browser/new_installer_offline_${VERSION}.jar*
echo Uploading to emu
rsync -v new_installer* sha1test.jar* wrapper* osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/installer/
echo ssh osprey.vm.bytemark.co.uk "cp /var/www/downloads/alpha/installer/new_installer_offline.jar /var/www/downloads/alpha/installer/new_installer_offline_${VERSION}.jar"
ssh osprey.vm.bytemark.co.uk -- "cp /var/www/downloads/alpha/installer/new_installer_offline.jar /var/www/downloads/alpha/installer/new_installer_offline_${VERSION}.jar"
rsync -v new_installer_offline.jar.sig osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/installer/new_installer_offline_${VERSION}.jar.sig
OLDVERSION=$[$VERSION-5]
echo Deleting old version ${OLDVERSION}
ssh osprey.vm.bytemark.co.uk rm /var/www/downloads/alpha/installer/new_installer_offline_${OLDVERSION}.jar
ssh osprey.vm.bytemark.co.uk -- "cp /var/www/downloads/alpha/.registry .; cat /var/www/downloads/alpha/.registry | sed \"s/new_installer_offline.jar .*$/new_installer_offline.jar installer\/new_installer_offline_${VERSION}.jar/\" > new-registry ; cat new-registry > /var/www/downloads/alpha/.registry"
ssh-agent -k
