#!/bin/bash

# variables used by this script
# these variables are probably different for everybody
# so create $HOME/.freenetrc and override those with your desired values.

RELEASE_DIRECTORY="/usr/src/cvs/eclipse-workspace/FreenetReleased"
WORKSPACE_FRED="/usr/src/cvs/eclipse-workspace/fred/"
START_STOP_SSH_AGENT="1"

# override these variables, if necessary
if [ -f "${HOME}/.freenetrc" ]; then
	. "${HOME}/.freenetrc"
fi

TEMPLOC=`mktemp -d`
cp -a "${WORKSPACE_FRED}/" $TEMPLOC
echo Copied data
cd $TEMPLOC/fred/
GITVERSION=`cat "${RELEASE_DIRECTORY}/freenet.tag"`
VERSION=`cat "${RELEASE_DIRECTORY}/freenet.build"`
echo Git version is $GITVERSION version is $VERSION
git checkout $GITVERSION || exit
git reset --hard
git clean -dfx
cp -a . ../fred-clean
mkdir lib 2>/dev/null
cp "${RELEASE_DIRECTORY}/freenet-ext.jar" lib/freenet-ext.jar || exit
mkdir lib/freenet; cp lib/freenet-ext.jar lib/freenet/
REQUIRED_EXT=`cat src/freenet/node/NodeStarter.java | sed -n "s/^.*REQUIRED_EXT_BUILD_NUMBER = \([0-9]*\).*$/\1/p"`
RECOMMENDED_EXT=`cat src/freenet/node/NodeStarter.java | sed -n "s/^.*RECOMMENDED_EXT_BUILD_NUMBER = \([0-9]*\).*$/\1/p"`
if [[ -n $REQUIRED_EXT ]]; then echo Required ext: $REQUIRED_EXT; else echo Required ext version not found; exit 3; fi
if [[ -n $RECOMMENDED_EXT ]]; then echo Recommended ext: $RECOMMENDED_EXT; else echo Recommended ext version not found; exit 3; fi
echo "contrib.version.min=$REQUIRED_EXT" >> override.properties
echo "contrib.version.rec=$RECOMMENDED_EXT" >> override.properties
ant -f build-clean.xml || exit

# start ssh agent and collect password
if [ "${START_STOP_SSH_AGENT}" == "1" ]; then
	eval `ssh-agent -s`
	ssh-add
fi

rsync --delete -rz javadoc/* osprey.vm.bytemark.co.uk:/var/www/freenet-website/javadocs
# Jars
mv dist/freenet.jar freenet-${GITVERSION}.jar || exit
sha1sum freenet-${GITVERSION}.jar > freenet-${GITVERSION}.jar.sha1
cp freenet-${GITVERSION}.jar ~toad
echo Copying freenet-${GITVERSION}.jar*
cp freenet-${GITVERSION}.jar* "{RELEASE_DIRECTORY}/" || exit
echo Checking that ${RELEASE_DIRECTORY}/freenet-build0${VERSION}.jar exists.
[[ -e "${RELEASE_DIRECTORY}/freenet-build0${VERSION}.jar" ]] || exit
echo Checking that ${RELEASE_DIRECTORY}/freenet-${GITVERSION}.jar exists.
[[ -e "${RELEASE_DIRECTORY}/freenet-${GITVERSION}.jar" ]] || exit
rm "{RELEASE_DIRECTORY}/freenet.jar"
ln -s "{RELEASE_DIRECTORY}/freenet-${GITVERSION}.jar" "{RELEASE_DIRECTORY}/freenet.jar"
su - toad -c "gpg --sign --detach-sign freenet-${GITVERSION}.jar"
cp ~toad/freenet-${GITVERSION}.jar.sig .
rm ~toad/freenet-${GITVERSION}.jar*
cp freenet-${GITVERSION}.jar* /var/lib/freenet-experimental/
cp freenet-${GITVERSION}.jar.sig "{RELEASE_DIRECTORY}/" || exit
cp freenet-${GITVERSION}.jar* ~browser
chmod a+r ~browser/freenet-${GITVERSION}.jar*
rsync -vz freenet-${GITVERSION}.jar* osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/
echo Uploaded new snapshot to emu
rm freenet-${GITVERSION}.jar*
echo "http://downloads.freenetproject.org/alpha/freenet-${GITVERSION}.jar" > ../freenet-testing-latest.jar.url
rsync -vz ../freenet-testing-latest.jar.url osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/freenet-testing-latest.jar.url
rsync -vz ../freenet-testing-latest.jar.url osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/freenet-stable-latest.jar.url
ssh osprey.vm.bytemark.co.uk -- "cp /var/www/downloads/alpha/.registry .; cat /var/www/downloads/alpha/.registry | sed \"s/freenet-testing-latest.jar .*$/freenet-testing-latest.jar freenet-${GITVERSION}.jar/;s/freenet-stable-latest.jar .*$/freenet-stable-latest.jar freenet-${GITVERSION}.jar/\" > new-registry ; cat new-registry > /var/www/downloads/alpha/.registry; rm /var/www/downloads/alpha/freenet-testing-build-*"
echo Uploaded new pointers
cd ..
rm -Rf fred
mv fred-clean freenet-${GITVERSION}
rm -Rf freenet-${GITVERSION}/.git
tar cjf freenet-${GITVERSION}-source.tar.bz2 freenet-${GITVERSION}
cp freenet-${GITVERSION}-source.tar.bz2* ~toad/
su - toad -c "gpg --sign --detach-sign freenet-${GITVERSION}-source.tar.bz2"
cp ~toad/freenet-${GITVERSION}-source.tar.bz2.sig .
cp freenet-${GITVERSION}-source.tar.bz2* ~browser/
chmod a+r ~browser/freenet-${GITVERSION}-source.tar.bz2
rsync -vz freenet-${GITVERSION}-source.tar.bz2 osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/freenet-${GITVERSION}-source.tar.bz2
rsync -vz freenet-${GITVERSION}-source.tar.bz2.sig osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/freenet-${GITVERSION}-source.tar.bz2.sig
cp freenet-${GITVERSION}-source.tar.bz2* /usr/src/cvs/eclipse-workspace/FreenetReleased
echo Uploaded source code to emu
rm -Rf $TEMPLOC
cd
/root/bin/compare-l10n ${VERSION}

# shut down the ssh agent
if [ "${START_STOP_SSH_AGENT}" == "1" ]; then
	ssh-agent -k
fi
