#!/bin/bash
TEMPLOC=`mktemp -d`
cp -a /usr/src/cvs/eclipse-workspace/fred/ $TEMPLOC
echo Copied data
cd $TEMPLOC/fred/
git reset --hard
mkdir lib 2>/dev/null
cp /usr/src/cvs/eclipse-workspace/FreenetReleased/freenet-ext.jar lib/freenet-ext.jar; mkdir lib/freenet; cp lib/freenet-ext.jar lib/freenet/
ant clean -Dsuppress.gjs=false || exit
rm lib/freenet-cvs-snapshot.jar
cp -a . ../fred-clean
REQUIRED_EXT=`cat src/freenet/node/NodeStarter.java | sed -n "s/^.*REQUIRED_EXT_BUILD_NUMBER = \([0-9]*\).*$/\1/p"`
RECOMMENDED_EXT=`cat src/freenet/node/NodeStarter.java | sed -n "s/^.*RECOMMENDED_EXT_BUILD_NUMBER = \([0-9]*\).*$/\1/p"`
if [[ -n $REQUIRED_EXT ]]; then echo Required ext: $REQUIRED_EXT; else echo Required ext version not found; exit 3; fi
if [[ -n $RECOMMENDED_EXT ]]; then echo Recommended ext: $RECOMMENDED_EXT; else echo Recommended ext version not found; exit 3; fi
echo "contrib.version.min=$REQUIRED_EXT" >> override.properties
echo "contrib.version.rec=$RECOMMENDED_EXT" >> override.properties
ant -f build-clean.xml || exit
GITVERSION=`git describe --always --abbrev=40`
export JAVA_HOME=/usr/lib/jvm/java-1.5.0-sun
export PATH=${JAVA_HOME}/bin:${JAVA_HOME}/jre/bin:$PATH
mv dist/freenet.jar freenet-${GITVERSION}-snapshot.jar || exit
sha1sum freenet-${GITVERSION}-snapshot.jar > freenet-${GITVERSION}-snapshot.jar.sha1
cp freenet-${GITVERSION}-snapshot.jar ~toad/
su - toad -c "gpg --sign --detach-sign freenet-${GITVERSION}-snapshot.jar"
cp ~toad/freenet-${GITVERSION}-snapshot.jar.sig .
eval `ssh-agent -s`
ssh-add
rsync -vvz freenet-${GITVERSION}-snapshot.jar* osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/
cp freenet-${GITVERSION}-snapshot.jar* /usr/src/cvs/eclipse-workspace/FreenetReleased/pre/
rm freenet-${GITVERSION}-snapshot.jar*
echo Uploaded new snapshot
echo "http://downloads.freenetproject.org/alpha/freenet-${GITVERSION}-snapshot.jar" > ../freenet-testing-latest.jar.url
rsync -vvz ../freenet-testing-latest.jar.url osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/freenet-testing-latest.jar.url
ssh osprey.vm.bytemark.co.uk -- "cat /var/www/downloads/alpha/.registry | sed \"s/freenet-testing-latest.jar .*$/freenet-testing-latest.jar freenet-${GITVERSION}-snapshot.jar/\" > new-registry ; cat new-registry > /var/www/downloads/alpha/.registry"
echo Uploaded new pointers
cd ..
rm -Rf fred
mv fred-clean fred
cd fred
rm -Rf .git
tar cjf ../freenet-${GITVERSION}-source.tar.bz2 .
rsync -vvz ../freenet-${GITVERSION}-source.tar.bz2 osprey.vm.bytemark.co.uk:/var/www/downloads/alpha/freenet-${GITVERSION}-source.tar.bz2
echo Uploaded source
rm -Rf $TEMPLOC
ssh-agent -k
(echo ClientHello; echo Name=Toad-update-${GITVERSION}; echo ExpectedVersion=2; echo End; echo ClientPut; echo "URI=CHK@"; echo "Identifier=freenet-${GITVERSION}-snapshot.jar"; echo Verbosity=1023; echo MaxRetries=-1; echo UploadFrom=disk; echo "Filename=/usr/src/cvs/eclipse-workspace/FreenetReleased/pre/freenet-${GITVERSION}-snapshot.jar"; echo "TargetFilename=freenet-${GITVERSION}-snapshot.jar"; echo Persistence=forever; echo PriorityClass=1; echo Global=true; echo End; echo ClientPut; echo "URI=CHK@"; echo "Identifier=freenet-${GITVERSION}-snapshot.jar.sig"; echo Verbosity=1023; echo MaxRetries=-1; echo UploadFrom=disk; echo "Filename=/usr/src/cvs/eclipse-workspace/FreenetReleased/pre/freenet-${GITVERSION}-snapshot.jar.sig"; echo "TargetFilename=freenet-${GITVERSION}-snapshot.jar.sig"; echo Persistence=forever; echo PriorityClass=1; echo Global=true; echo End) | nc 127.0.0.1 9481
