#!/bin/bash
# FIXME clean up, give --help etc.

# Deploy the website on the webserver using locally-reviewed commit IDs.

source freenet-scripts-common
readConfig
getBuildInfo
websiteID=$(cd "$websiteOfficialDir"; git rev-parse --verify master)

# Both git describe and git rev-parse --verify will give a tag if it exists.
echo Fred ID "$commitID"
echo Website ID "$websiteID"
scp $targetHost google_drive_links "$remoteDeployPrefix"
ssh $targetHost -- "$remoteDeployPrefixCommand ${remoteDeployPrefix}deploy-website -u --force-website-id $websiteID --force-fred-id $commitID"
