#!/bin/bash
FILENAME=$1
rm -f seednodes.fref
wget --no-check-cert https://checksums.freenetproject.org/latest/seednodes.fref -O seednodes.fref || exit 1
java -Xmx128M -cp /usr/src/cvs/eclipse-workspace/Freenet\ 0.7/lib/freenet-ext.jar:/usr/src/cvs/eclipse-workspace/Freenet\ 0.7/bin/ freenet.node.simulator.BootstrapPullTest amphibian-servalan.dyndns.org > $FILENAME 2>&1
exit $?
