#!/bin/bash
TEMP=`mktemp`
(su - freenet-tests /var/local/run-seednode-test) > $TEMP 2>&1
STATUS=$?
time=`date +"/var/www/freenet/tests/seednodes/%Y/%m/%d/output.%H-%M-%S.log"`
mkdir -p `dirname $time`

if [[ $STATUS == 0 ]]; then
	mv $TEMP $time
	chown root.root $time
	(echo Subject: Seednodes test completed; echo; cat $time | grep "^RESULT:"; echo; echo Log at $time; echo ".") | /usr/sbin/sendmail toad
else
	mv $TEMP ${time}.failed
	chown root.root ${time}.failed
	(echo Subject: Seednodes test FAILED; echo; cat ${time}.failed; echo ".") | /usr/sbin/sendmail toad
fi
