#!/bin/bash

source freenet-scripts-common || exit
readConfig || exit

# Packages on Debian Wheezy
# For building Java: openjdk-6-jdk ant
# For release management: rsync, coreutils, diffutils, gnupg, less, wget, perl
# For building the Windows installer: xvfb, wine, wine-gecko, mono-runtime
# For avoiding repeated password entry: gnupg-agent openssh-client
# It would be interesting to have the scripts repo without git, but might as well.
sudo apt-get install git openjdk-6-jdk rsync ant coreutils gnupg diffutils less wget xvfb wine perl gnupg-agent openssh-client mono-runtime wine-gecko-1.4 netcat

mkdir -p "$releaseDir"

# countryDataFile might have a directory that doesn't exist (it is very likely
# to by default) so create it.
# NOTE: Beware of downloading this file multiple times per day. Those who host
# it are apparently very happy to add to their blacklist.
mkdir -p $(dirname "$countryDataFile")
wget software77.net/geo-ip/?DL=4 -O "$countryDataFile"

# Clone if not set up already.
if [ ! -d "$fredDir" ]; then
    require "Clone Freenet repository into \"$fredDir\"?"
    git clone git@github.com:freenet/fred-staging.git "$fredDir" || exit
else
    # TODO: Check that fred-staging is the origin.
    echo "Assuming origin is official fred-staging."
fi

if [ ! -d "$installerDir" ]; then
    require "Clone Freenet installer into \"$installerDir\"?"
    git clone https://github.com/freenet/java_installer-official.git "$installerDir" || exit
fi

if [ ! -d "$wininstallerDir" ]; then
    require "Clone Freenet Windows installer into \"$wininstallerDir\"?"
    git clone https://github.com/freenet/wininstaller-official.git "$wininstallerDir" || exit
fi

if [ ! -d "$websiteOfficialDir" ]; then
    require "Clone Freenet website into \"$websiteOfficialDir\"?"
    git clone https://github.com/freenet/website-official.git "$websiteOfficialDir"
fi

pushd "$fredDir"
# tag-build assumes fred-staging as the `origin` remote, and fred-official as the `stable` remote.
git remote add stable git@github.com:freenet/fred-official.git
