#!/bin/bash

# TODO: Is this desirable behavior?
if [[ -z $1 ]]; then
	echo Usage: sign-installer-jars /some/dir/containing/jars
	exit 1
fi
cd "$1"

# TODO: Is this an appropriate place to have a list of things that are signed? It's not just signing jars, which makes the name inaccurate. It's intended to sign a very specific list of files. Would it be appropriate to use this to sign everything, or is having the checksum and signature generation spread throughout useful? Why is this not part of the installer script itself?
for x in new_installer.jar new_installer_offline.jar sha1test.jar wrapper_Darwin.zip wrapper_Linux.zip wrapper_windows.zip; do
    echo Signing ${x}
    rm -f "${x}.sig"
    # TODO: Binary sha512sum.
    sha1sum "${x}" > "${x}.sha1"
    gpg --sign --detach-sign "${x}"
    # In case it generates an invalid signature. This happened before.
    gpg --verify "${x}.sig" || exit 1
done
