#!/bin/bash
if [[ -z $1 ]]; then
	echo Usage: sign-installer-jars /some/dir/containing/jars
	exit 1
fi
cd $1

for x in new_installer.jar new_installer_offline.jar sha1test.jar wrapper_Darwin.zip wrapper_Linux.zip wrapper_windows.zip; do echo Signing ${x}; rm -f ${x}.sig; sha1sum ${x} > ${x}.sha1; gpg --sign --detach-sign ${x}; gpg --verify ${x}.sig || exit 1; done
