#!/bin/bash
source freenet-scripts-common || exit
readConfig || exit
DIFF=`git diff`
if [[ ! -z $DIFF ]]; then
        echo You did not commit the files!
        echo "$DIFF"
        exit 1
fi
DIFF=
if grep TESTNET src/freenet/node/Version.java ; then echo TRYING TO RELEASE A TESTNET BUILD AS A REAL BUILD ; exit 2; fi
BUILD=$1
if [[ -z $BUILD ]]; then 
	echo Usage: tag-build 1234
	echo 1234 is the build number.
	exit 3
fi
if ! grep "buildNumber = $BUILD;" src/freenet/node/Version.java ; then echo YOU MUST UPDATE src/freenet/node/Version.java; exit 4; fi
TAG=$(printf 'build%05d' "$BUILD")
PREVBUILD=$(($BUILD-1))
PREVTAG=$(printf 'build%05d' "$PREVBUILD")
FULLCHANGELOG=$releaseDir/changelog.full.$TAG.txt
CHANGELOG=$releaseDir/changelog.short.$TAG.txt
echo Releasing build $TAG
echo Previous build was $PREVTAG
echo Please enter developer changelog:
cat > $FULLCHANGELOG || exit 10
echo Please enter end-user-friendly changelog:
cat > $CHANGELOG || exit 11
TEMP=`mktemp`
cat $CHANGELOG > $TEMP
echo >> $TEMP
echo "Developer changelog:" >> $TEMP
echo >> $TEMP
cat $FULLCHANGELOG >> $TEMP
echo >> $TEMP
git log ${PREVTAG}.. | grep Author: | sort | uniq >> $TEMP || exit 9
echo
echo
echo Combined changelog as will be tagged:
echo
cat $TEMP
echo
echo Confirm release of $TAG? y/n
read x
if [[ $x != "y" ]]; then
	rm $TEMP
	git tag -d $TAG
	echo FAILED
	exit 5
fi
git tag -s $TAG -F $TEMP || exit 8
git push --tags origin
git push stable $TAG
git push origin
git push stable
git push --tags stable
echo $TAG > /usr/src/cvs/eclipse-workspace/FreenetReleased/freenet.tag || exit 6
echo $BUILD > /usr/src/cvs/eclipse-workspace/FreenetReleased/freenet.build
BRANCH=`git branch | grep "^*" | cut -b 3-`
if test $BRANCH != "master" && test $BRANCH != "next"; then
	echo Merging back into master
	git checkout master
	git merge --ff-only $TAG || exit 7
	echo Delete branch $BRANCH? y/n
	read x
	if [[ $x == "y" ]]; then
		git branch -d $BRANCH
		git push origin :$BRANCH
		echo Deleted branch $BRANCH
	else
		git checkout $BRANCH
	fi
	git checkout next
	git merge master
	git push origin next
	git push origin master
	git push stable master
	git push stable next
	git checkout next
fi
rm $TEMP
