#!/bin/bash
set -o errexit

# Load configuration and utility functions.
source freenet-scripts-common || exit

bookmarkPath="$fredDir/src/freenet/clients/http/staticfiles/defaultbookmarks.dat"

update-bookmarks.py --verbose --host=$fcpHost --port=$fcpPort "$bookmarkPath"

# Commit updated bookmarks if any changes are made.
cd "$fredDir"
if [[ -n "$(git diff "$bookmarkPath")" ]]
then
    git commit -m "Update default bookmark editions" "$bookmarkPath"
fi
