#!/bin/bash
set -o errexit

# Load configuration and utility functions.
source freenet-scripts-common || exit

versionPath="$fredDir/src/freenet/node/Version.java"

./update_version.py "$1" "$versionPath"

cd "$fredDir"
# Ensure it still builds.
echo "Checking that the modified code builds."
./gradlew --parallel --offline clean jar && git commit -m "Build $1" -m "" -m "See tag for changelog." "$versionPath"
