#!/bin/bash

source freenet-scripts-common || exit

cd "$seedrefsDir" || exit

rm -f "$seedrefsPath"

for ref in *
do
    cat "$ref" >> "$seedrefsPath" || exit
    # Newline in case a reference is missing one on the last line.
    echo >> "$seedrefsPath" || exit
done

if grep -ni "priv" "$seedrefsPath"
then
    echo "Found private noderef at above line in $seedrefsPath"
    exit 1
fi

if egrep -n "^End" "$seedrefsPath" | egrep -v "End$"
then
    echo "Missing newline after End at above line in $seedrefsPath"
    exit 1
fi

# TODO: sha256/512
sha1sum "$seedrefsPath" > "$seedrefsPath.sha1" || exit

# gpg will prompt before overwriting, which is not desirable here.
rm -f "$seedrefsPath.gpg"
gpg -o "$seedrefsPath.gpg" --sign "$seedrefsPath" || exit

rsync -v "$seedrefsPath" "$seedrefsPath.sha1" "$seedrefsPath.gpg" "$targetHost:/var/www/downloads/alpha/opennet/"
